services:
  db:
    image: mysql:latest
    container_name: itam_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itam
      MYSQL_USER: itam_user
      MYSQL_PASSWORD: itam_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
    networks:
      - itam_net  
  itam:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: itam:1.0
    container_name: itam
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: itam_user
      DB_PASS: itam_pass
      DB_NAME: itam
      JWT_SECRET: secret
      JWT_ALGORITHM: HS256    
    networks:
      - itam_net
  
volumes:
  mysql_data:

networks:
  itam_net:
    driver: bridge
